from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import text

from ..database import get_db, engine
from ..models import Dataset
from ..schemas import DataPreviewResponse

router = APIRouter(
    prefix="/data-preview",
    tags=["Data Preview"]
)

@router.get("/{dataset_id}", response_model=DataPreviewResponse)
def get_data_preview(
    dataset_id: str, 
    page: int = Query(1, ge=1), 
    page_size: int = Query(50, ge=1, le=500),
    db: Session = Depends(get_db)
):
    dataset = db.query(Dataset).filter(Dataset.id == dataset_id).first()
    
    if not dataset:
        raise HTTPException(status_code=404, detail="Dataset not found")

    table_name = dataset.table_name
    offset = (page - 1) * page_size

    try:
        # We use raw SQL because the table is dynamic.
        # It's safe here since table_name is generated by our backend (dataset_<uuid>)
        with engine.connect() as connection:
            result = connection.execute(text(f"SELECT * FROM {table_name} LIMIT :limit OFFSET :offset"), {"limit": page_size, "offset": offset})
            rows = [dict(row._mapping) for row in result]
            
            # Get column names
            columns = list(rows[0].keys()) if rows else []
            
        return DataPreviewResponse(
            total_rows=dataset.row_count,
            page=page,
            page_size=page_size,
            columns=columns,
            data=rows
        )
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching data preview: {str(e)}")
